stages:
  - build
  - test
  - deploy

variables:
  GIT_DEPTH: "1"

npm_build:
  stage: build
  tags:
    - linux
  script:
    - npm ci
    - npm run build

# npm_test:
#   stage: test
#   tags:
#     - linux
#   script: npm run test
#   dependencies:
#     - npm_build
