stages:
  - install
  - lint
  - test
  - build
  - deploy

npm_ci:
  stage: install
  tags:
    - linux
  script: npm ci
  artifacts:
    paths:
      - node_modules

.build_base:
  tags:
    - linux
  dependencies:
    - npm_ci

npm_lint:
  extends: build
  stage: lint
  tags:
    - linux
  script: npm run lint

npm_build:
  extends: .build_base
  stage: build
  tags:
    - linux
  script: npm run build

