stages:
  - lint
  - build
  - test
  - deploy

before_script:
  - npm ci

npm_lint:
  stage: lint
  tags:
    - linux
  script: npm run lint

npm_build:
  stage: build
  tags:
    - linux
  script: npm run build

# npm_test:
#   stage: test
#   tags:
#     - linux
#   script: npm run test
#   dependencies:
#     - npm_build
